DROP DATABASE IF EXISTS XXXXSystem;
CREATE DATABASE XXXXSystem;
USE XXXXSystem;

CREATE TABLE SysManager
(
	ManagerID VARCHAR(20) PRIMARY KEY,
	ManagerPWD VARCHAR(10) NOT NULL
);

INSERT INTO SysManager VALUES('admin','admin');

CREATE TABLE SysUser
(
	SysUserID VARCHAR(20) PRIMARY KEY,
	SysUserPWD VARCHAR(10) NOT NULL
);